### ISSUE TITLE
Doesn't detect code block right after list

### ISSUE THREAD

**Issue by sickill** [pragdave/earmark#143]
Hey, I noticed that when I put my indented code block after a list (doesn't matter how many empty lines between them) it doesn't render the code block properly:

```
iex(1)> Earmark.as_html!("* one\n* two\n* three\n\n    some code")
"<ul>\n<li>one\n</li>\n<li>two\n</li>\n<li><p>three</p>\n<p>some code</p>\n</li>\n</ul>\n"
```

Adding any text between list and code block fixes it:

```
iex(2)> Earmark.as_html!("* one\n* two\n* three\n\ntext\n\n    some code")
"<ul>\n<li>one\n</li>\n<li>two\n</li>\n<li>three\n</li>\n</ul>\n<p>text</p>\n<pre><code>some code</code></pre>\n"
```

**Comment by sickill** [comment]
As a workaround I tried:

```
<pre>
<code>
my code here
</code>
</pre>
```

But it adds extra leading and trailing empty lines to my code snippet.

**Comment by RobertDober** [comment]
@sickill Thank you for your report, hopefully getting to work on a fix soon.

**Comment by RobertDober** [comment]
I was a little fast with this one, actually GFM does what you want and that about is it.

The best I could do is to parse the code as suggested by you **iff** the  `gfm: true` option is set.

But it definitely is not a bug.

I believe that the following markdown should be standard an shoudl do what you need:
```iex
iex(31)> Earmark.as_html!("* a\n```\nyour code\n```") |> IO.puts
<ul>
<li>a
</li>
</ul>
<pre><code class="">your code</code></pre>

```

**Comment by RobertDober** [comment]
I was a little fast with this one, actually GFM does what you want and that about is it.

The best I could do is to parse the code as suggested by you **iff** the  `gfm: true` option is set.

But it definitely is not a bug.

I believe that the following markdown should be standard an shoudl do what you need:
```iex
iex(31)> Earmark.as_html!("* a\n```\nyour code\n```") |> IO.puts
<ul>
<li>a
</li>
</ul>
<pre><code class="">your code</code></pre>

```

**Comment by sickill** [comment]
Thanks, this does the trick. Not sure whether the behavior I described is a bug or not, but I'm fine with closing this issue.

**Comment by RobertDober** [comment]
Glad that helped.

I will leave the issue open, because if the `gfm: true` option is given it might be nice to behave exactly as GFM behaves ;).

Quite happy though that I can treat it low priority.

-----
Some background info in case you are interested:

Most implementations do the same thing as `Earmark`.

As you might know there is no strict _definition_ for markdown, although _commonmark_ tries hard.

Dave decided to not blindly follow _commonmark_ which is quite strict and complicated but we are pretty compatible by following the mainstream on [Babelmark](http://johnmacfarlane.net/babelmark2/)
