### ISSUE TITLE
How to "override" renderer functions?

### ISSUE THREAD

**Issue by sn3p** [pragdave/earmark#207]
For example, I like to render custom links based on the app host name (similar to #145):

```ex
@app_hosts ["example.com", "www.example.com"]

def link(url, text), do
  case String.starts_with?(url, @app_host) do
    true -> ~s[<a href="#{url}">#{text}</a>],
    false -> ~s[<a href="#{url}" target="_blank" class="external-link">#{text}</a>]
  end
end
```

**What is best practice for a use case like this?**

- I know about [IAL](https://github.com/pragdave/earmark#adding-html-attributes-with-the-ial-extension), but I don't want to bother users with "advanced" features like this.
  ```md
  [Example](http://www.example.com){:target='_blank'}
  ```
- I prefer not to use a [plugin](https://github.com/pragdave/earmark#plugins) where users have to prefix `$$` to make it work.
- I prefer not to clone the whole default [`Earmark.HtmlRenderer`](https://github.com/pragdave/earmark/blob/master/lib/earmark/html_renderer.ex) to create a custom renderer when I only need custom links.

Thanks in advance!

**Comment by RobertDober** [comment]
I am afraid that this is quite complicated, even with #145 in place (certainly not this year, maybe never) you still would need to customize the whole HTML Renderer, which, of course would be much easier to do.

The question is, and I will give you some thought for sure, how we could expose that kind of feature so that you need to define only, say, the LinkRenderer, maybe protocols, maybe pluggable functions for subrenderers that fall back to the default?

**Comment by sn3p** [comment]
@RobertDober thanks for considering this. Output manipulation (#145) would be great, although in some cases it would make more sense to override the render functions.

I think it should be possible making the renderer functions overridable using [`defoverridable/1`](https://hexdocs.pm/elixir/Kernel.html#defoverridable/1).
Also see https://elixirforum.com/t/behaviours-defoverridable-and-implementations/3338

**Something like this maybe (untested):**

```ex
defmodule Earmark.HtmlRenderer.Behaviour do
  @callback link :: any
  # ...
end

defmodule Earmark.HtmlRenderer do
  defmacro __using__(_opts) do
    quote do
      @behaviour Earmark.HtmlRenderer.Behaviour
      
      def link(url, text), do: ~s[<a href="#{url}">#{text}</a>]
      def link(url, text, nil), do: ~s[<a href="#{url}">#{text}</a>]
      def link(url, text, title), do: ~s[<a href="#{url}" title="#{title}">#{text}</a>]

      # ...

      defoverridable Earmark.HtmlRenderer.Behaviour
    end
  end
end

defmodule MyCustomRenderer do
  use Earmark.HtmlRenderer

  def link(url, text), do: ~s[<a href="#{url}" class="custom-link">#{text}</a>]
end
```

---

**For now I got it working like this:**

```ex
defmodule MyApp.ModuleExtension do
  defmacro extends(module) do
    module = Macro.expand(module, __CALLER__)
    functions = module.__info__(:functions)

    signatures =
      Enum.map(functions, fn {name, arity} ->
        args =
          Enum.map(0..arity, fn i ->
            {String.to_atom(<<?x, ?A + i>>), [], nil}
          end)

        {name, [], tl(args)}
      end)

    quote do
      defdelegate unquote(signatures), to: unquote(module)
      defoverridable unquote(functions)
    end
  end
end

defmodule MyApp.MarkdownRenderer do
  import MyApp.ModuleExtension

  extends(Earmark.HtmlRenderer)

  def link(url, text), do: ~s[<a href="#{url}" class="custom">#{text}</a>]
end
```

source: https://gist.github.com/josevalim/ff41078606cfe0e55eaf

**Comment by RobertDober** [comment]
I am **really**, **really** afraid to close ourselves into an exposed API.

If @pragdave made the renderer pluggable and not extendable I suspect that it was for that reason. I just do not want to close ourselves into a cage here, because if we made all render functions public and overrideable that seems too fat an API too me.

The more I think about this, the more I believe that Earmark shall not expose its code to be _reused_, that is not its purpose.

Once we expose an AST, that would establish a  contract and I would just love to see other projects spring into life around that, but Earmark itself shall stay as lean as possible, we are just too close to the metal.

**Comment by pragdave** [comment]
I think that's a really good call.

Dave
