### ISSUE TITLE
Wrong rendering when a list item terminates with a escaped backtick

### ISSUE THREAD

**Issue by josevalim** [pragdave/earmark#208]
The following code:

```elixir
var = ~S"""
## Exiting the shell

There are a few ways to quit the IEx shell:

  * via the `BREAK` menu (available via `Ctrl+C`) by typing `q`, pressing enter
  * by hitting `Ctrl+C`, `Ctrl+C`
  * by hitting `Ctrl+\`

If you are connected to remote shell, it remains alive after disconnection.
"""

IO.puts Earmark.as_html! var
```

prints:

```
<no file>:7: warning: Closing unclosed backquotes ` at end of input
<h2>Exiting the shell</h2>
<p>There are a few ways to quit the IEx shell:</p>
<ul>
<li>via the <code class="inline">BREAK</code> menu (available via <code class="inline">Ctrl+C</code>) by typing <code class="inline">q</code>, pressing enter
</li>
<li>by hitting <code class="inline">Ctrl+C</code>, <code class="inline">Ctrl+C</code>
</li>
<li>by hitting <code class="inline">Ctrl+\</code>

If you are connected to remote shell, it remains alive after disconnection.
</li>
</ul>
```

As you can see, it warns that we have unclosed backticks but backticks cannot be escaped with `\` according to the spec. See common mark: https://spec.commonmark.org/0.28/#backslash-escapes

See this Elixir issues too: https://github.com/elixir-lang/elixir/issues/8382

Thanks for the great project! :heart:

**Comment by RobertDober** [comment]
This is tricky because the potential change will not be backwards compatible.

@pragdave  will correct me if I remember wrongly but Commonmark compliance was not really a goal of Earmark.

As I cannot see any working workaround short of this (adding a space)...

```elixir
Earmark.as_html " ``hello \\` ``"
{:ok, "<p> <code class=\"inline\">hello \\`</code></p>\n", []
```

... I will tag this as a bug for now and will try to free some time to look into it.

@josevalim thanks for your kind words, but I recon that you have misspasted the second link.

And generally if common mark compliance is desired for `ex_doc` we would have some quite work ahead of us...

**Comment by josevalim** [comment]
Fixed the link, thanks!

**Comment by RobertDober** [comment]
I just realized, that we, strip the whitespace at the beginning and ending of code spans in the workaround proposed above.

(Which is also in accordance with Commonmark https://spec.commonmark.org/0.28/#code-spans)

However we do not collapse whitespace inside code spans, right now!

So that might help you to get the documentation right without waiting for a 1.3 release...

**Comment by RobertDober** [comment]
@pragdave I have fixed this and prepared a release as v1.3 as we are having two mild backwards incompatibilities here. This issue and #90.

Ok for you?

**Comment by pragdave** [comment]
fine by me. thanks again for all you do.

**Comment by RobertDober** [comment]
1.3.0 published
