### ISSUE TITLE
Pure links causes UnicodeConversionError on sanitize

### ISSUE THREAD

**Issue by StephaneRob** [pragdave/earmark#243]
Can't sanitize html after converting from markdown.

ex:
 
```elixir
"foo (https://test.com) … bar" 
|> Earmark.as_html!(pure_links: true)

=> "<p>foo (<a href=\"https://test.com\">https://test.com</a>) … bar</p>\n"

# but

"foo (https://test.com)… bar" 
|> Earmark.as_html!(pure_links: true)

=> <<60, 112, 62, 102, 111, 111, 32, 40, 60, 97, 32, 104, 114, 101, 102, 61, 34, 104, 116, 116, 112, 115, 58, 47, 47, 116, 101, 115, 116, 46, 99, 111, 109, 41, 226, 34, 62, 104, 116, 116, 112, 115, 58, 47, 47, 116, 101, 115, 116, 46, ...>>
```

If i try to sanitize the second example I get `invalid encoding starting at <<226, 34>>`

**UPDATE**

If I sanitize before converting from markdown, I get `** (Jason.EncodeError) invalid byte` when render json view on phoenix

**Comment by RobertDober** [comment]
@StephaneRob that is a nice catch of you
I have an idea, (the yecc parser might not like utf8 too match) but I will keep investigating.

Please let me know about the priority of this, I'd love to release 1.3.3 with #240 but biting on nails right now.

However if this is a serious problem (actually it is, but not bugging anyone so far I guess :blush:) I will try to make a hotfix release.

**Comment by StephaneRob** [comment]
@RobertDober thank you very much for this fast answer.

It is actually a serious problem for me, but I also understand that you have lot of to do.
Tell me I can submit a PR to help.

**Comment by RobertDober** [comment]
I was wondering, if you do not use pure links you could use 1.3.2 from hex instead master from github however there might be more non utf8 regexen and I guess there is a reason you used pure_links. 
But just to mention it.

A PR would be welcome, if you have few time just adding the `u` flags to all regexen concerned should be sufficient.
If you have more time adding some tests, either in `acceptance/utf8` or `regression/i243-utf8-problems` would be great.

Here is an edge case BTW, although right now URLS cannot be UTF8 (IIRC) this still is, well, not nice
```
iex(1)> Earmark.as_html!("[è](https://www.google.çom)")
"<p><a href=\"https://www.google.%C3%A7om\">è</a></p>\n"
iex(2)>
```

Not sure this can be fixed in yecc though.

Merci beaucoup pour votre cooperation, et salutations de Narbonne 🌞 .

**Comment by RobertDober** [comment]
Thanx again for your PR
