### ISSUE TITLE
Fenced code block for UML

### ISSUE THREAD

**Issue by garthk** [pragdave/earmark#252]
I'd like to replace fenced code blocks with the `plantuml` language with SVGs generated by that tool, e.g.:

    ```plantuml
    @startuml
    testdot
    @enduml
    ```
→
![](http://s.plantuml.com/imgw/graphviz-dot-4zfzrtjl.png)

My editors and history rely on fenced code blocks, so I'm afraid the `$$` plugin syntax is a show-stopper. Would you take a PR on invoking plugins using fenced code block syntax with the plugin name as the "language"?

Is there some other, more practical point to intervene to add a custom syntax for pretty-printing?

Failing those, could this be easily built given #145?

**Comment by RobertDober** [comment]
I will deprecate plugins anyway.

I guess #145 would really be the way to go, but my plan is to expose an AST and not to worry about a zillion of possible granularity and performance issues. 

Would the exposure of an AST solve your problem, somehow I guess not, right?

But imagine the exposure of an AST with a configurable conversion tool, **outisde** of Earmark, I believe that would cut it nicely w/o too much burden on Earmark itself.

Looking forward on hearing your opinion.

**Comment by garthk** [comment]
> Would the exposure of an AST solve your problem

It's plausible: just a matter of replacing nodes representing the fenced code block with other nodes representing `![alt text](https://example.com/4zfzrtjl.png)`. Are there nodes suitable for writing the image to disk? That'd feel better than predicting the destination path and writing it, especially as it'd permit some subsequent AST transform in the chain to move, rename, or modify the file if required.

**Comment by pragdave** [comment]
We do stuff like this all the time at the Bookshelf. We often inject
generated content into books.

However, our approach is not too have one-tool-to-rule-them-all. Instead we
have a multi stage pipeline, where each book writer can create their own
stages for their own particular needs. In our case, the result is XML, not
HTML, but the principle it's the same.

The nice thing about this approach is that the author can choose where in
the pipe to put each processor. They don't even have to include markdown at
all, it theirs rather use their own import language (some have).

It also has the nice benefit of letting you choose whether your
preprocessor runs before or after the markdown step.

So, to solve your problem in a general way, is really like to see something
like a scriptable GenStage, rather than add something to earmark.

Cheers


Dave
