### ISSUE TITLE
Earmark.as_plaintext/1

### ISSUE THREAD

**Issue by arjan** [pragdave/earmark#312]
Would you accept a PR for a function that strips markdown and returns the text without formatting? I found myself writing one, and it seems like a logical addition to me.

**Comment by RobertDober** [comment]
depends, but probably you should release your own hex package that uses `Earmark.as_ast`
but I'll gladly have a look  keeping an open mind

**Comment by arjan** [comment]
The code is fairly simple, to the likes of:

```elixir
  def strip_markdown(markdown) do
    with {:ok, ast, []} <- Earmark.as_ast(markdown) do
      markdown_ast_to_iodata(ast)
      |> IO.chardata_to_string()
    else
      _ ->
        markdown
    end
  end

  defp markdown_ast_to_iodata(ast) when is_list(ast) do
    ast
    |> Enum.map(fn
      v when is_binary(v) ->
        v

      {_tag, _attr, ast} ->
        markdown_ast_to_iodata(ast)
    end)
  end
```

**Comment by RobertDober** [comment]
I understand why this could go into Earmark, because it is too small for a package.

I guess I will merge this into Earmark but the idea is definitely to get it out of Earmark again and into a hex package kind of `EarmarkTransformers` (pun name of course), and that, once

(i) the AST is stable
(ii) more _standard_ transformations will be part of Earmark

Would that be ok with you?

The rationale is that we want Earmark to be as lean as possible because it is a dependency for virtual all hex packages as far as I know. (Although one can create the hexdocs exactly how we do it).

**Comment by RobertDober** [comment]
so in case you are preparing a PR please add two or three test cases into `test/acceptance/transform`.
Thx

**Comment by arjan** [comment]
Awesome, I'll do that!
