### ISSUE TITLE
Version 1.4.5 adds unexpected newlines in HTML

### ISSUE THREAD

**Issue by nathanl** [pragdave/earmark#359]
Rendered HTML contains extra white space and newlines in version 1.4.5 as compared to 1.4.4. 

Version 1.4.4:

```elixir
Earmark.as_html!("oh *hi* there") #=> "<p>oh <em>hi</em> there</p>\n"
```

Version 1.4.5

```elixir
Earmark.as_html!("oh *hi* there") #=> "<p>\n  oh \n  <em>\n    hi\n  </em>\n   there\n</p>\n"
```

This is a minor problem, but the additional whitespace broke some tests in an application I work on, where we had expectations like

```elixir
assert body =~ "Some <em>other</em> widget"
```

Maybe it should be listed as a breaking change in the notes?

**Comment by RobertDober** [comment]
Thank you for the report, this will indeed be addressed in #329 but that is not obvious from the description so I will leave your issue open too.

**Comment by RobertDober** [comment]
May I allow myself an unsolicitated remark: While I completely strive to issue consistent HTML and the switch to AST let me stray from that path, I did also believe that there was no contract about how the HTML looks like.

Again, I consider this radical change a bug, however....

I'd rather not test HTML textually but structurally, because that is where the semantic differences lie, might I suggest to parse HTML with [Floki](https://hex.pm/packages/floki) and make your assertions after that.

That said I will not introduce changes to format on purpose, but am unwilling to really adhere to a contract.

Thank you for your understanding.

**Comment by nathanl** [comment]
@RobertDober Good points. I'll take a look at using Floki in our tests.
