### ISSUE TITLE
Incorrect parsing of code example

### ISSUE THREAD

**Issue by kipcole9** [pragdave/earmark#380]
## Environment

* Earmark 1.4.9
* Earmark_parser 1.4.9
* Elixir 1.10.3
* OTP 22.3

## Current Behaviour
```elixir
iex> Earmark.as_ast "{:error, \"Required options are missing. Required options are [:name, :digits]\"}"
{:error,
 [
   {"p", [],
    ["{:error, \"Required options are missing. Required options are [:name, :digits]\"}"],
    %{}}
 ],
 [
   {:warning, 1,
    "Illegal attributes [\":digits]\\\"\", \"[:name,\", \"are\", \"options\", \"Required\", \"missing.\", \"are\", \"options\", \"\\\"Required\", \"error,\"] ignored in IAL"}
 ]}
```
## Example
From a piece of production code:
```elixir
      iex> MyApp.Cldr.Currency.new(:XAA, name: "Private Use Name")
      {:error, "Required options are missing. Required options are [:name, :digits]"}
```
## Expected Behaviour

No parser error.

**Comment by RobertDober** [comment]
This is indeed an IAL extension and not text, it is also related to https://github.com/RobertDober/earmark_parser and not Earmark as `as_ast` is a delegator, it will become deprecated, then this will be clearer.

You need to escape the first accolade of the IAL

```elixir
iex(2)> Earmark.as_ast "\\{:error, \"Required options are missing. Required options are [:name, :digits]\"}"
{:ok,
 [
   {"p", [],
    ["{:error, \"Required options are missing. Required options are [:name, :digits]\"}"],
    %{}}
 ], []}
```

HTH

**Comment by kipcole9** [comment]
Apologies for sounding a bit slow but I'm confused as to why I need to escape anything in a code example that is a doctest? And similarly, I don't know what form such an escape would - nor indeed if it means my doctest would no longer work?

**Comment by RobertDober** [comment]
It is indeed not obvious at all so no apologies needed.

IALs are an Earmark extension to markdown, and as `ex_doc` uses Earmark (now EarmarkParser) your code is just an IAL.

I did not explain this to you because I did not realize that you were redirected from an ex_doc issue, so I thought you knew what IAL was, never assume, (you know that old pun I guess).

Also please forgive me for having been so short in my explanations, but in more than 4 years now I **never** had an issue with IAL so you caught me by surprise and furthermore I was releasing the whole morning :sweat: 

Please look at the README for more information about IAL

I am happy to answer any further question of course, no problem at all.
