### ISSUE TITLE
Option to minify HTML output

### ISSUE THREAD

**Issue by alexgleason** [pragdave/earmark#391]
We're using Earmark in [Pleroma](https://git.pleroma.social/pleroma/pleroma), a self-hosted social media platform, to allow users to write posts in Markdown.

Pleroma is federated, so it has to handle posts from other ActivityPub implementations. Sometimes these implementations will use newlines instead of `<br>` tags to indicate line breaks, so we apply `white-space: pre-wrap;` on the text content to preserve this formatting. There's more info [in this issue](https://git.pleroma.social/pleroma/pleroma/-/issues/1375).

This is a problem when using Earmark, since it will always output prettified HTML. Eg for this input: `hello\n\nworld!` we get this output: `<p>\nhello</p>\n<p>\nworld!</p>\n`. With `white-space: pre-wrap;` applied it treats these `\n` very literally and creates a lot of unwanted whitespace.

I'd like the ability to pass an option, maybe like `%{minify: true}`, to format the output like so: `<p>hello</p><p>world!</p>`

For now I've created a function that seems to handle most cases:

```elixir
def minify(text, "text/html") do
  text
  |> String.replace(">\n", ">")
  |> String.replace(">  ", ">")
  |> String.replace("  <", "<")
end
```

(There also seems to be issues with extraneous spaces, which the last two lines try to resolve, eg:)

```
iex(4)> Earmark.as_html! "<ul><li>one</li><li>two</li><li>three</li><li>four</li></ul>"
"<ul>\n  <li>one</li><li>two</li><li>three</li><li>four</li></ul>\n"
```

**Comment by RobertDober** [comment]
Sorry for this inconvenience, this will be fixed but I had foreseen to do that later because so far nobody was really impacted (ex_doc does not use the transformer anymore).

I cannot promise to get this into 1.4, it really depends on my upcoming schedule.

A PR would be great the goal is to have quite compact, but reasonable HTML, something like not indented with line breaks before and after block tags (but not all, e.g. not `<code>`)

**Comment by RobertDober** [comment]
Oh BTW I was not thinking about an option, this should be the default behavior IMHO

**Comment by RobertDober** [comment]
However I was talking about something completely different, 😓 

I was talking about rendering Markdown to HTML, not HTML, please note that, that kind of input is not even supported (it kinda works by chance)

```elixir
Earmark.as_html! "<ul><li>one</li><li>two</li><li>three</li><li>four</li></ul>"
``` 

Please see https://github.com/pragdave/earmark/issues/390 and https://github.com/pragdave/earmark#html-blocks


As mentioned this shall be handled https://github.com/RobertDober/earmark_parser/issues/7 

I will keep this issue open and change the rendering to a more compact (and possibly minified) output.

But before the related `EarmarkParser` issue, nothing can be done

**Comment by alexgleason** [comment]
Solving it with Markdown it HTML is what we're trying to do. My example above was just to demonstrate a case with extraneous spaces, but the issue is mainly about newlines added from Markdown to HTML output. Thank you!

**Comment by RobertDober** [comment]
IIUC we have two issues 
- Rendering is bogus because of two much whitespace (which is a bug)
- HTML is not totally parsed (which is specified) and might lead to unexpected results, will go away with EarmarkParser's issue https://github.com/RobertDober/earmark_parser/issues/7

Therefore in theory I can fix the first bug if I have time 😨  (or could accept a bug request)

Can you confirm please?

**Comment by alexgleason** [comment]
> Rendering is bogus because of two much whitespace (which is a bug)

Yes, you're correct. The issue is extraneous newlines. Thank you!

**Comment by feld** [comment]
Hello, checking in on this

**Comment by rinpatch** [comment]
I have a draft commit for this https://github.com/rinpatch/earmark/commit/2e8b4dc893438eba9874c011611235e924ab3b72, it works perfectly in my testing, however causes 110 tests to fail due to expected fixtures containing newlines. Unfortunately my attempts to automate the fixture rework ran into some edge cases and modifying it all manually is not my idea of fun to say the least. I might get back to it at some point, but would appreciate if someone who has a smarter idea could attempt it.

**Comment by RobertDober** [comment]
@rinpatch can you please make a PR against branch i391_minify_html, I will gladly have a look
