### ISSUE TITLE
Option to define the links target

### ISSUE THREAD

**Issue by dwellmind** [pragdave/earmark#441]
I suppose rendering HTML with links with a target (here `_blank`) is a commun case.

I wrote this after looking the documentation.

```elixir
markdown
|> Earmark.as_html!(
  registered_processors: [
    Earmark.TagSpecificProcessors.new(
      {"a", &Earmark.AstTools.merge_atts_in_node(&1, target: "_blank")}
    )
  ]
)
```

It works. However, it is a bit verbose and makes us dive into Earmark internals.

Do you think an option (e.g. named `links_target`) is conceivable?

**Comment by RobertDober** [comment]
Hmm IIRC this has been discussed already and rejected because oftentimes the target of the link depends on the type/domain of the target link.
That is why the above approach which is extensible to provide more control.

Please also be aware that the option would not go into `Earmark`  but `EarmarkParser`.

Again if IIRC I repeat myself: Maybe a set of predefined processors in a different lib would be a nice idea and I have redesigned Earmark to expose an AST exactly for that kind of use case.

However I regret but do not have the resources to implement that kind of features.

**Comment by RobertDober** [comment]
Même pas pour un Breton désolé :cry: Kenavo

**Comment by RobertDober** [comment]
BTW I am sorry that from the docs it is not clear that these are not internals but exposed with a well defined, alas complicated API, to be used by the expert user.

**Comment by dwellmind** [comment]
I understand, it just felt weird to me.

Kenavo!
