### ISSUE TITLE
XSS vunerability

### ISSUE THREAD

**Issue by remiq** [pragdave/earmark#58]
Hi,

I've just tested this (http://stackoverflow.com/questions/1690601/markdown-and-xss/6823393#6823393) in Earmark 0.2.0 and the output is vunerable.

How to recreate:

    Earmark.to_html """
    > hello <a name="n"
    > href="javascript:alert('xss')">*you*</a>
    """

results in `"<blockquote><p>hello <a name=\"n\"\nhref=\"javascript:alert('xss')\"><em>you</em></a></p>\n</blockquote>\n"` which includes `<a href="javascript:alert('xss')">you</a>`.

**Comment by remiq** [comment]
7 out of 12 markdown implementations have the same issue: 
http://johnmacfarlane.net/babelmark2/?text=%3E+hello+%3Ca+name%3D%22n%22%0A%3E+href%3D%22javascript%3Aalert%28%27xss%27%29%22%3E*you*%3C%2Fa%3E

**Comment by RobertDober** [comment]
Thanx for the report I am going to look into this.

**Comment by RobertDober** [comment]
@remiq just for your information and in case you'd care to share your thoughts: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/elixir-lang-talk/kSgQ1tWJQe4

**Comment by redvers** [comment]
Markdown standard requires that HTML be passed right through if it meets certain criteria:

"An HTML block is a group of lines that is treated as raw HTML (and will not be escaped in HTML output)"
-- http://spec.commonmark.org/0.24/#html-blocks

Including <script>:  http://spec.commonmark.org/0.24/#example-132

And that's the intent!
"Text between < and > that looks like an HTML tag is parsed as a raw HTML tag and will be rendered in HTML without escaping. Tag and attribute names are not limited to current HTML tags, so custom tags (and even, say, DocBook tags) may be used"
-- http://spec.commonmark.org/0.24/#raw-html

Perhaps a docpatch is in order?

**Comment by RobertDober** [comment]
@redvers Your feedback is most welcome. The more I read and think about this I feel that maybe it is not Earmark's responsability to filter XSS. However in that case the burden would fall upon `ex_doc`, right, did you mean that with docpatch? Probably an XSS html filter should be written for Elixir/Erlang, I was asking a question on the ML on this, no result so far ;(.
I really shall not take any decision on this without having some input from the community, ex_doc developers and of course Dave.  

BTW We do not really follow the common mark spec and I feel that we shall not, as it is way to demanding.
That said I respect their efforts and their more pragmatic approach to provide Babelmark2 is most valuable to me. I have also contacted John MacFarlane on that topic.

@pragdave your insight is sought for. 

Whatever the final decision on this issue is, at least we shall make a disclaimer in the dox, so many folx -- me included -- forget about XSS.

**Comment by pragdave** [comment]
I agree with what you say—it isn't our job.

I also don't really support CommonMark—I think it's missing the point.

So I'm very happy with things as they are.

**Comment by RobertDober** [comment]
Thank you @pragdave I will close the issue and add a note to the dox.
