### ISSUE TITLE
Bug in link using parthesis

### ISSUE THREAD

**Issue by eksperimental** [pragdave/earmark#70]
check the [Wikipedia article on PATH](https://en.wikipedia.org/wiki/PATH_(variable))

It will link to `https://en.wikipedia.org/wiki/PATH_(variable`

**Comment by eksperimental** [comment]
for testing ideas:
http://meta.stackexchange.com/questions/13501/links-to-urls-containing-parentheses

**Comment by RobertDober** [comment]
Thx for the report, nice example ;).

**Comment by RobertDober** [comment]
@eksperimental concerning the release of this I would like to know how important this fix is to you. That is because we are in a refactoring pgase right now. I still believe that we could release the code as it is correct but overly complicated. So if this is not important maybe we will release better code later. Thank you for your input.

**Comment by eksperimental** [comment]
There is no rush for the release. Thanks for the fix

**Comment by RobertDober** [comment]
good to know, thx
