### ISSUE TITLE
Last item in lists is not wrapped in <p>

### ISSUE THREAD

**Issue by ericmj** [pragdave/earmark#93]
You can see the formatting issue on https://hex.pm/docs/tasks#hex_publish.

**Comment by RobertDober** [comment]
Frankly I cannot. Can you provide markdown input and expected html output?

**Comment by ericmj** [comment]
You can see the some of the text of the text in lists is bold and some is not. If you cannot see it on the website you can inspect the source.

Here is the markdown: https://github.com/hexpm/hex/blob/master/lib/mix/tasks/hex/publish.ex#L39-L52

**Comment by RobertDober** [comment]
I succeeded to extract an offending case

````iex(30)> md = """
...(30)> # HL
...(30)>
...(30)>   * one
...(30)>
...(30)>   * two
...(30)> """
"# HL\n\n  * one\n \n  * two\n"
iex(31)> Earmark.to_html md
"<h1>HL</h1>\n<ul>\n<li><p>one</p>\n</li>\n<li>two\n</li>\n</ul>\n"
```

**Comment by ericmj** [comment]
I was meaning to find a reproducing case but got bogged on an unrelated issue. I am sorry for making you find it.

Thank you @RobertDober :heart:

**Comment by RobertDober** [comment]
np @ericmj I just needed to read the title...

**Comment by RobertDober** [comment]
I kinda have a fix for this, honestly the semantics of list items in paras goes a little over my head right now. 
Neither from the code, nor from experiments on Babelmark I managed to really understand when to put them and when not.

Therefore, for starters I decided all <li> are wrapped in <p>s if one is, somehow defying the parser's semantics in the renderer. Ugly and maybe incorrect.

@pragdave your guidance would be appreciated.

 And anybody I would be grateful for some pointers or explanations on that account.

**Comment by pragdave** [comment]
My understanding is that the <p>s are added if there is a blank line after
the item.

**Comment by RobertDober** [comment]
Thank you Dave I will review the code a little more to be sure to not have violated that principle. After merging this issue branch it might be a good idea to release 1.0.2.

**Comment by ericmj** [comment]
> My understanding is that the <p>s are added if there is a blank line after the item.

Don't you always have to terminate the list with a blank line after the last item?

**Comment by RobertDober** [comment]
@ericmj that is true, and BTW, if you are interested in  technical details, it was the source of the bug, as the parser did not put the "spaced" flag on the last list item, never. And it is this __never__ which still bugs me.

I guess one can trust the tests and the code is releasable in case the bugfix is urgently needed. Otherwise I'd like to investigate some further, but that will take some time.

**Comment by ericmj** [comment]
A bugfix is not needed urgently so on my part please take your time.

**Comment by RobertDober** [comment]
thx, well noted

**Comment by RobertDober** [comment]
I did some research here are three possible behaviors.

1. wrap a `li`'s content into a `p` if there is a space before **or** after the item.
(many implementations do that)

1. Wrap with`p` in case **any** line has a space before **or** after the item.
(some, and amongst them commonmark, which is a surprise to me, do that)

1. For minimal backward incompatibility wrap with `p` if an item is followed by an empty line **or the last line** is preceded by an empty line. N.B. That implies a `p` for the last but one item too.

I like 2. best for it's simplicity, and because that is what we have right now on master. However it might be the most violent concerning backward incompatibility.

**Comment by RobertDober** [comment]
@pragdave I guess we have enough in the 1.0.2 milestone to release. Do you agree? Thank you in advance.
